---
# handlers file for react
- name: run the container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    ports:
      - "3000:3000"
    state: started
